classDiagram
    class Space1{
    }
    class Role1{
    }
    class Agent1{
    }
    class Capability1{
    }
    class Event1{
    }
    class Document1{
    }
    class LogicalDevice1{
    }
    class BuildingComponent1{
    }
    class Collection1{
    }
    class Asset1{
    }
    Portfolio1 <|-- Collection1
    AssetCollection1 <|-- Collection1
    SpaceCollection1 <|-- Collection1
    LogicalController1 <|-- LogicalDevice1
    LogicalGateway1 <|-- LogicalDevice1
    LogicalServer1 <|-- LogicalDevice1
    Component1 <|-- Asset1
    Furniture1 <|-- Asset1
    ArchitecturalAsset1 <|-- Asset1
    Equipment1 <|-- Asset1
    Sensor1 <|-- Capability1
    Actuator1 <|-- Capability1
    Parameter1 <|-- Capability1
    Person1 <|-- Agent1
    Organization1 <|-- Agent1
    LeaseContract1 <|-- Document1
    RoofOuter1 <|-- BuildingComponent1
    Facade1 <|-- BuildingComponent1
    Floor1 <|-- BuildingComponent1
    Wall1 <|-- BuildingComponent1
    Slab1 <|-- BuildingComponent1
    Terrace1 <|-- BuildingComponent1
    VirtualBuildingComponent1 <|-- BuildingComponent1
    RoofInner1 <|-- BuildingComponent1
    Balcony1 <|-- BuildingComponent1
    Zone1 <|-- Space1
    Level1 <|-- Space1
    Building1 <|-- Space1
    SubBuilding1 <|-- Space1
    Land1 <|-- Space1
    Region1 <|-- Space1
    Room1 <|-- Space1
    Lease1 <|-- Event1
    ArchitecturalAssetCollection1 <|-- AssetCollection1
    FurnitureCollection1 <|-- AssetCollection1
    EquipmentCollection1 <|-- AssetCollection1
    TenantUnit1 <|-- SpaceCollection1
    Campus1 <|-- SpaceCollection1
    RealEstate1 <|-- SpaceCollection1
    Apartment1 <|-- SpaceCollection1
    BarrierAsset1 <|-- ArchitecturalAsset1
    Pump1 <|-- Component1
    HVACMixingBox1 <|-- Component1
    Fan1 <|-- Component1
    Tank1 <|-- Component1
    HeatTracing1 <|-- Component1
    HVACHeatingMethod1 <|-- Component1
    Valve1 <|-- Component1
    DuctConnection1 <|-- Component1
    ElectricalBus1 <|-- Component1
    HVACCoolingMethod1 <|-- Component1
    Chair1 <|-- Furniture1
    Bed1 <|-- Furniture1
    Meter1 <|-- Equipment1
    FireProtectionEquipment1 <|-- Equipment1
    ConveyanceEquipment1 <|-- Equipment1
    PlumbingEquipment1 <|-- Equipment1
    ICTEquipment1 <|-- Equipment1
    HVACEquipment1 <|-- Equipment1
    ElectricalEquipment1 <|-- Equipment1
    LightingEquipment1 <|-- Equipment1
    SecurityEquipment1 <|-- Equipment1
    PowerSensor1 <|-- Sensor1
    HumiditySensor1 <|-- Sensor1
    StatusSensor1 <|-- Sensor1
    FlowSensor1 <|-- Sensor1
    MassSensor1 <|-- Sensor1
    PressureSensor1 <|-- Sensor1
    OccupancySensor1 <|-- Sensor1
    IlluminanceSensor1 <|-- Sensor1
    MotionSensor1 <|-- Sensor1
    PeopleCountSensor1 <|-- Sensor1
    TemperatureSensor1 <|-- Sensor1
    EnergySensor1 <|-- Sensor1
    TVOCSensor1 <|-- Sensor1
    VolumeSensor1 <|-- Sensor1
    CO2Sensor1 <|-- Sensor1
    Setpoint1 <|-- Parameter1
    Company1 <|-- Organization1
    Department1 <|-- Organization1
    WallInner1 <|-- Wall1
    LoadingReceivingRoom1 <|-- Room1
    Workshop1 <|-- Room1
    BackOffice1 <|-- Room1
    FoodHandlingRoom1 <|-- Room1
    Office1 <|-- Room1
    ExhibitionRoom1 <|-- Room1
    RecordingRoom1 <|-- Room1
    Stairwell1 <|-- Room1
    PersonalHygiene1 <|-- Room1
    EducationalRoom1 <|-- Room1
    ExerciseRoom1 <|-- Room1
    RecreationalRoom1 <|-- Room1
    StaffRoom1 <|-- Room1
    DressingRoom1 <|-- Room1
    Laboratory1 <|-- Room1
    RestingRoom1 <|-- Room1
    LaundryRoom1 <|-- Room1
    ServiceShaft1 <|-- Room1
    ElevatorShaft1 <|-- Room1
    Shelter1 <|-- Room1
    Bedroom1 <|-- Room1
    Entrance1 <|-- Room1
    MeditationRoom1 <|-- Room1
    ElevatorRoom1 <|-- Room1
    Bathroom1 <|-- Room1
    CleaningRoom1 <|-- Room1
    UtilitiesRoom1 <|-- Room1
    Reception1 <|-- Room1
    LivingRoom1 <|-- Room1
    Library1 <|-- Room1
    Atrium1 <|-- Room1
    Auditorium1 <|-- Room1
    Hallway1 <|-- Room1
    CloakRoom1 <|-- Room1
    Theater1 <|-- Room1
    CopyingRoom1 <|-- Room1
    Garage1 <|-- Room1
    WasteManagementRoom1 <|-- Room1
    RetailRoom1 <|-- Room1
    TreatmentRoom1 <|-- Room1
    MultiPurposeRoom1 <|-- Room1
    Storage1 <|-- Room1
    Cinema1 <|-- Room1
    ConversationRoom1 <|-- Room1
    ConferenceRoom1 <|-- Room1
    MothersRoom1 <|-- Room1
    SecurityRoom1 <|-- Room1
    Workspace1 <|-- Zone1
    HVACZone1 <|-- Zone1
    Stadium1 <|-- Building1
    Hospital1 <|-- Building1
    VirtualBuilding1 <|-- Building1
    ShoppingMall1 <|-- Building1
    School1 <|-- Building1
    EquipmentGroup1 <|-- EquipmentCollection1
    System1 <|-- EquipmentCollection1
    AccessPanel1 <|-- BarrierAsset1
    Partition1 <|-- BarrierAsset1
    Window1 <|-- BarrierAsset1
    Door1 <|-- BarrierAsset1
    PlumbingHeatTracing1 <|-- PlumbingEquipment1
    PlumbingHeatTracing1 <|-- HeatTracing1
    Luminaire1 <|-- LightingEquipment1
    LightingController1 <|-- LightingEquipment1
    SensorEquipment1 <|-- ICTEquipment1
    Controller1 <|-- ICTEquipment1
    ITHardware1 <|-- ICTEquipment1
    DataNetworkEquipment1 <|-- ICTEquipment1
    Gateway1 <|-- ICTEquipment1
    AudioVisualEquipment1 <|-- ICTEquipment1
    ITRack1 <|-- ICTEquipment1
    AirHandlingUnit1 <|-- HVACEquipment1
    HVACWaterTreatment1 <|-- HVACEquipment1
    HVACTank1 <|-- Tank1
    HVACTank1 <|-- HVACEquipment1
    TerminalUnit1 <|-- HVACEquipment1
    HVACPump1 <|-- Pump1
    HVACPump1 <|-- HVACEquipment1
    HeatExchanger1 <|-- HVACEquipment1
    AirFilter1 <|-- HVACEquipment1
    Damper1 <|-- HVACEquipment1
    CondensingUnit1 <|-- HVACEquipment1
    HVACValve1 <|-- Valve1
    HVACValve1 <|-- HVACEquipment1
    HVACFan1 <|-- HVACEquipment1
    UnitHeater1 <|-- HVACEquipment1
    HVACHeatTracing1 <|-- HeatTracing1
    HVACHeatTracing1 <|-- HVACEquipment1
    CoolingTower1 <|-- HVACEquipment1
    Chiller1 <|-- HVACEquipment1
    Elevator1 <|-- ConveyanceEquipment1
    ElevatorMachine1 <|-- ConveyanceEquipment1
    Escalator1 <|-- ConveyanceEquipment1
    MovingWalkway1 <|-- ConveyanceEquipment1
    ElectricalGenerationStorageEquipment1 <|-- ElectricalEquipment1
    ElectricalDistributionEquipment1 <|-- ElectricalEquipment1
    PlumbingValve1 <|-- Valve1
    PlumbingValve1 <|-- PlumbingEquipment1
    PlumbingTank1 <|-- Tank1
    PlumbingTank1 <|-- PlumbingEquipment1
    Boiler1 <|-- PlumbingEquipment1
    Drain1 <|-- PlumbingEquipment1
    PlumbingPump1 <|-- Pump1
    PlumbingPump1 <|-- PlumbingEquipment1
    PlumbingWaterTreatment1 <|-- PlumbingEquipment1
    PlumbingFixture1 <|-- PlumbingEquipment1
    AirCompressor1 <|-- PlumbingEquipment1
    WaterHeater1 <|-- PlumbingEquipment1
    ThermalMeter1 <|-- Meter1
    GasMeter1 <|-- Meter1
    WaterMeter1 <|-- Meter1
    ElectricityMeter1 <|-- Meter1
    VideoSurveillanceEquipment1 <|-- SecurityEquipment1
    AccessControlEquipment1 <|-- SecurityEquipment1
    IntrusionDetectionEquipment1 <|-- SecurityEquipment1
    FireSuppressionEquipment1 <|-- FireProtectionEquipment1
    FireAlarmEquipment1 <|-- FireProtectionEquipment1
    FireExtinguisherTroubleSensor1 <|-- StatusSensor1
    DamperStatusSensor1 <|-- StatusSensor1
    LeakSensor1 <|-- StatusSensor1
    FireExtinguisherRemovedSensor1 <|-- StatusSensor1
    FanStatusSensor1 <|-- StatusSensor1
    ThermalEnergySensor1 <|-- EnergySensor1
    ElectricalEnergySensor1 <|-- EnergySensor1
    MassFlowSensor1 <|-- FlowSensor1
    AirFlowSensor1 <|-- FlowSensor1
    WaterFlowSensor1 <|-- FlowSensor1
    WaterTemperatureSensor1 <|-- TemperatureSensor1
    AirTemperatureSensor1 <|-- TemperatureSensor1
    ThermalPowerSensor1 <|-- PowerSensor1
    ElectricalPowerSensor1 <|-- PowerSensor1
    FlowSetpoint1 <|-- Setpoint1
    CO2Setpoint1 <|-- Setpoint1
    TemperatureSetpoint1 <|-- Setpoint1
    HumiditySetpoint1 <|-- Setpoint1
    Classroom1 <|-- EducationalRoom1
    GroupRoom1 <|-- EducationalRoom1
    SmallStudyRoom1 <|-- EducationalRoom1
    FittingRoom1 <|-- RetailRoom1
    OfficeLandscape1 <|-- Office1
    PhoneBooth1 <|-- Office1
    OfficeRoom1 <|-- Office1
    LaboratoryDry1 <|-- Laboratory1
    LaboratoryWet1 <|-- Laboratory1
    DisabledToilet1 <|-- PersonalHygiene1
    ShowerRoom1 <|-- PersonalHygiene1
    Toilet1 <|-- PersonalHygiene1
    Sauna1 <|-- PersonalHygiene1
    MailRoom1 <|-- BackOffice1
    TreatmentWaitingRoom1 <|-- TreatmentRoom1
    DishingRoom1 <|-- FoodHandlingRoom1
    BarRoom1 <|-- FoodHandlingRoom1
    CookingRoom1 <|-- FoodHandlingRoom1
    Pentry1 <|-- FoodHandlingRoom1
    CafeteriaRoom1 <|-- FoodHandlingRoom1
    DiningRoom1 <|-- FoodHandlingRoom1
    ShelterGasLock1 <|-- Shelter1
    ShelterRoom1 <|-- Shelter1
    SprinklerRoom1 <|-- UtilitiesRoom1
    CableRoom1 <|-- UtilitiesRoom1
    DataServerRoom1 <|-- UtilitiesRoom1
    ClimateControlRoom1 <|-- UtilitiesRoom1
    Cabinet1 <|-- UtilitiesRoom1
    ElectricityRoom1 <|-- UtilitiesRoom1
    ParkingSlotWarm1 <|-- Garage1
    BicycleGarage1 <|-- Garage1
    ParkingSlotCold1 <|-- Garage1
    MainEntrance1 <|-- Entrance1
    ServiceEntrance1 <|-- Entrance1
    MeterEquipmentGroup1 <|-- EquipmentGroup1
    ElectricalEquipmentGroup1 <|-- EquipmentGroup1
    LightingEquipmentGroup1 <|-- EquipmentGroup1
    ICTEquipmentGroup1 <|-- EquipmentGroup1
    HVACEquipmentGroup1 <|-- EquipmentGroup1
    PlumbingEquipmentGroup1 <|-- EquipmentGroup1
    SecurityEquipmentGroup1 <|-- EquipmentGroup1
    ConveyanceEquipmentGroup1 <|-- EquipmentGroup1
    FireProtectionEquipmentGroup1 <|-- EquipmentGroup1
    LightingSystem1 <|-- System1
    PlumbingSystem1 <|-- System1
    FireProtectionSystem1 <|-- System1
    ITSystem1 <|-- System1
    ControlsSystem1 <|-- System1
    HVACSystem1 <|-- System1
    ElectricalSystem1 <|-- System1
    EthernetRouter1 <|-- DataNetworkEquipment1
    EthernetSwitchPort1 <|-- DataNetworkEquipment1
    NetworkSecurityEquipment1 <|-- DataNetworkEquipment1
    WirelessAccessPoint1 <|-- DataNetworkEquipment1
    EthernetSwitch1 <|-- DataNetworkEquipment1
    Server1 <|-- ITHardware1
    CAVBox1 <|-- TerminalUnit1
    FanCoilUnit1 <|-- TerminalUnit1
    VAVBox1 <|-- TerminalUnit1
    SteamUnitHeater1 <|-- UnitHeater1
    ElectricUnitHeater1 <|-- UnitHeater1
    HotWaterUnitHeater1 <|-- UnitHeater1
    HVACBackflowPreventer1 <|-- HVACValve1
    HVACSolenoidValve1 <|-- HVACValve1
    HVACShutOffValve1 <|-- HVACValve1
    HVACPressureReducingStation1 <|-- HVACValve1
    HVACGlobeValve1 <|-- HVACValve1
    HVACPressureReducingValve1 <|-- HVACValve1
    HVACCheckValve1 <|-- HVACValve1
    HVACBalancingValve1 <|-- HVACValve1
    MakeupAirUnit1 <|-- AirHandlingUnit1
    RooftopUnit1 <|-- AirHandlingUnit1
    DedicatedOutdoorAirSystem1 <|-- AirHandlingUnit1
    WaterFilter1 <|-- HVACWaterTreatment1
    CeilingFan1 <|-- HVACFan1
    ExhaustFan1 <|-- HVACFan1
    StairPressurizationFan1 <|-- HVACFan1
    TransferFan1 <|-- HVACFan1
    SupplyFan1 <|-- HVACFan1
    BackdraftDamper1 <|-- Damper1
    SmokeDamper1 <|-- Damper1
    FireDamper1 <|-- Damper1
    Switchgear1 <|-- ElectricalDistributionEquipment1
    ElectricalPanelboard1 <|-- ElectricalDistributionEquipment1
    TransferSwitch1 <|-- ElectricalDistributionEquipment1
    Busway1 <|-- ElectricalDistributionEquipment1
    Switchboard1 <|-- ElectricalDistributionEquipment1
    Transformer1 <|-- ElectricalDistributionEquipment1
    VariableFrequencyDrive1 <|-- ElectricalDistributionEquipment1
    Generator1 <|-- ElectricalGenerationStorageEquipment1
    UPS1 <|-- ElectricalGenerationStorageEquipment1
    Urinal1 <|-- PlumbingFixture1
    FlushometerValve1 <|-- PlumbingFixture1
    Sink1 <|-- PlumbingFixture1
    Toilet1 <|-- PlumbingFixture1
    Faucet1 <|-- PlumbingFixture1
    PlumbingSolenoidValve1 <|-- PlumbingValve1
    PlumbingPressureReducingValve1 <|-- PlumbingValve1
    PlumbingCheckValve1 <|-- PlumbingValve1
    PlumbingBalancingValve1 <|-- PlumbingValve1
    PlumbingGlobeValve1 <|-- PlumbingValve1
    PlumbingPressureReducingStation1 <|-- PlumbingValve1
    PlumbingBackflowPreventer1 <|-- PlumbingValve1
    PlumbingShutOffValve1 <|-- PlumbingValve1
    EjectorPump1 <|-- PlumbingPump1
    DomesticWaterPump1 <|-- PlumbingPump1
    IrrigationPump1 <|-- PlumbingPump1
    SumpPump1 <|-- PlumbingPump1
    RoofDrain1 <|-- Drain1
    FloorDrain1 <|-- Drain1
    TanklessWaterHeater1 <|-- WaterHeater1
    TankWaterHeater1 <|-- WaterHeater1
    PlumbingStorageTank1 <|-- PlumbingTank1
    PlumbingExpansionTank1 <|-- PlumbingTank1
    SurveillanceNVR1 <|-- VideoSurveillanceEquipment1
    SurveillanceCamera1 <|-- VideoSurveillanceEquipment1
    AccessReader1 <|-- AccessControlEquipment1
    RequestToExitDevice1 <|-- AccessControlEquipment1
    IntercomEntry1 <|-- AccessControlEquipment1
    AccessControlPanel1 <|-- AccessControlEquipment1
    CleanAgentEquipment1 <|-- FireSuppressionEquipment1
    SprinklerEquipment1 <|-- FireSuppressionEquipment1
    FireExtinguisher1 <|-- FireSuppressionEquipment1
    TelecommunicationRoom1 <|-- CableRoom1
    PlumbingPumpGroup1 <|-- PlumbingEquipmentGroup1
    ChilledWaterPlant1 <|-- HVACEquipmentGroup1
    HVACPumpGroup1 <|-- HVACEquipmentGroup1
    SprinklerPumpGroup1 <|-- FireProtectionEquipmentGroup1
    DCElectricalSystem1 <|-- ElectricalSystem1
    ACElectricalSystem1 <|-- ElectricalSystem1
    ModbusNetworkSystem1 <|-- ControlsSystem1
    BACnetNetworkSystem1 <|-- ControlsSystem1
    OPCDANetworkSystem1 <|-- ControlsSystem1
    OPCUANetworkSystem1 <|-- ControlsSystem1
    HVACAirSystem1 <|-- HVACSystem1
    HVACRefrigerantSystem1 <|-- HVACSystem1
    HVACWaterSystem1 <|-- HVACSystem1
    ITEthernetNetworkSystem1 <|-- ITSystem1
    FuelOilSystem1 <|-- PlumbingSystem1
    PlumbingWaterSystem1 <|-- PlumbingSystem1
    GasSystem1 <|-- PlumbingSystem1
    DrainageSystem1 <|-- PlumbingSystem1
    FireSuppressionSystem1 <|-- FireProtectionSystem1
    FireAlarmSystem1 <|-- FireProtectionSystem1
    FanPoweredBox1 <|-- VAVBox1
    VAVBoxReheat1 <|-- VAVBox1
    FanCoilUnitReheat1 <|-- FanCoilUnit1
    FireSmokeDamper1 <|-- FireDamper1
    AutomaticTransferSwitch1 <|-- TransferSwitch1
    ElectricalPanelboardMLO1 <|-- ElectricalPanelboard1
    ElectricalPanelboardMCB1 <|-- ElectricalPanelboard1
    Cogenerator1 <|-- Generator1
    UrinalFlushometer1 <|-- Urinal1
    UrinalWaterless1 <|-- Urinal1
    ToiletTank1 <|-- Toilet1
    ToiletFlushometer1 <|-- Toilet1
    GasTanklessWaterHeater1 <|-- TanklessWaterHeater1
    ElectricTanklessWaterHeater1 <|-- TanklessWaterHeater1
    ElectricTankWaterHeater1 <|-- TankWaterHeater1
    GasTankWaterHeater1 <|-- TankWaterHeater1
    CleanAgentTank1 <|-- CleanAgentEquipment1
    CleanAgentCabinet1 <|-- CleanAgentEquipment1
    SprinklerValve1 <|-- Valve1
    SprinklerValve1 <|-- SprinklerEquipment1
    SprinklerTank1 <|-- Tank1
    SprinklerTank1 <|-- SprinklerEquipment1
    FireSprinklerHead1 <|-- SprinklerEquipment1
    FirePump1 <|-- SprinklerEquipment1
    FirePump1 <|-- Pump1
    JockeyPump1 <|-- SprinklerEquipment1
    JockeyPump1 <|-- Pump1
    SprinklerHeatTracing1 <|-- SprinklerEquipment1
    SprinklerHeatTracing1 <|-- HeatTracing1
    PreActionEquipment1 <|-- SprinklerEquipment1
    HVACCondenserWaterSystem1 <|-- HVACWaterSystem1
    HVACHotWaterSystem1 <|-- HVACWaterSystem1
    HVACChilledWaterSystem1 <|-- HVACWaterSystem1
    HVACHumidificationSystem1 <|-- HVACWaterSystem1
    HVACConditionedAirSystem1 <|-- HVACAirSystem1
    HVACExhaustAirSystem1 <|-- HVACAirSystem1
    HVACTransferAirSystem1 <|-- HVACAirSystem1
    WasteVentDrainageSystem1 <|-- DrainageSystem1
    StormDrainageSystem1 <|-- DrainageSystem1
    PropaneSystem1 <|-- GasSystem1
    SteamSystem1 <|-- GasSystem1
    NaturalGasSystem1 <|-- GasSystem1
    WaterFeatureSystem1 <|-- PlumbingWaterSystem1
    IrrigationSystem1 <|-- PlumbingWaterSystem1
    DomesticWaterSystem1 <|-- PlumbingWaterSystem1
    SprinklerSystem1 <|-- FireSuppressionSystem1
    FanPoweredBoxReheat1 <|-- FanPoweredBox1
    PreActionCabinet1 <|-- PreActionEquipment1
    PreActionTank1 <|-- PreActionEquipment1
    SprinklerGlobeValve1 <|-- SprinklerValve1
    SprinklerBackflowPreventer1 <|-- SprinklerValve1
    SprinklerPressureReducingValve1 <|-- SprinklerValve1
    SprinklerSolenoidValve1 <|-- SprinklerValve1
    SprinklerCheckValve1 <|-- SprinklerValve1
    SprinklerPressureReducingStation1 <|-- SprinklerValve1
    SprinklerShutOffValve1 <|-- SprinklerValve1
    SprinklerBalancingValve1 <|-- SprinklerValve1
    HVACSupplyAirSystem1 <|-- HVACConditionedAirSystem1
    HVACReturnAirSystem1 <|-- HVACConditionedAirSystem1
    HVACOutsideAirSystem1 <|-- HVACConditionedAirSystem1
    HVACGreaseExhaustAirSystem1 <|-- HVACExhaustAirSystem1
    DomesticHotWaterRecircSystem1 <|-- DomesticWaterSystem1
    DomesticHotWaterSystem1 <|-- DomesticWaterSystem1
    DomesticColdWaterSystem1 <|-- DomesticWaterSystem1
    DomesticNonPotableWaterSystem1 <|-- DomesticWaterSystem1
    Space1 : +integer personOccupancy
    Space1 : +integer personCapacity
    Space1 : +servedBy()
    Space1 : +ownedBy()
    Space1 : +operatedBy()
    Space1 : +isPartOf()
    Space1 : +includedIn()
    Space1 : +hasPart()
    Space1 : +hasCapability()
    Space1 : +isLocationOf()
    Space1 : +constructedBy()
    Space1 : +architectedBy()
    Space1 : +string name
    Role1 : +string name
    Agent1 : +owns()
    Agent1 : +string name
    Agent1 : +hasRole()
    Capability1 : +serves()
    Capability1 : +isCapabilityOf()
    Capability1 : +string name
    Event1 : +dateTime hasUpdatedTime
    Event1 : +string hasTime
    Event1 : +dateTime hasStopTime
    Event1 : +dateTime hasStartTime
    Event1 : +dateTime hasReadTime
    Event1 : +dateTime hasPointInTime
    Event1 : +dateTime hasObservationTime
    Event1 : +double hasDuration
    Event1 : +dateTime hasDeletedTime
    Event1 : +dateTime hasCreatedTime
    Event1 : +string name
    Document1 : +string url
    Document1 : +string name
    LogicalDevice1 : +string IPAddress
    LogicalDevice1 : +isPartOf()
    LogicalDevice1 : +hasCapability()
    LogicalDevice1 : +hostedBy()
    LogicalDevice1 : +string name
    BuildingComponent1 : +isPartOf()
    BuildingComponent1 : +hasPart()
    BuildingComponent1 : +componentOfBuilding()
    BuildingComponent1 : +string name
    Collection1 : +string name
    Asset1 : +commissionedBy()
    Asset1 : +hosts()
    Asset1 : +string name
    Asset1 : +installedBy()
    Asset1 : +manufacturedBy()
    Asset1 : +servicedBy()
    Asset1 : +locatedIn()
    Asset1 : +hasCapability()
    Asset1 : +hasPart()
    Asset1 : +includedIn()
    Asset1 : +isPartOf()
    Asset1 : +servedBy()
    Asset1 : +serves()
    Asset1 : +date commissionDate
    Asset1 : +date expectedEndOfLife
    Asset1 : +duration expectedLife
    Asset1 : +string expectedReplacementCost
    Asset1 : +string initialCost
    Asset1 : +date installationDate
    Asset1 : +duration maintenanceInterval
    Asset1 : +date turnoverDate
    Asset1 : +string IPAddress
    Asset1 : +string MACAddress
    Asset1 : +string modelNumber
    Asset1 : +string physicalTagNumber
    Asset1 : +string serialNumber
    Portfolio1 : +includes()
    Equipment1 : +isFedBy()
    Equipment1 : +feeds()
    Sensor1 : +observes()
    Actuator1 : +observedBy()
    Person1 : +string lastName
    Person1 : +string image
    Person1 : +string givenName
    Person1 : +string gender
    Person1 : +string firstName
    Person1 : +string familyName
    Person1 : +isMemberOf()
    Organization1 : +string logo
    Organization1 : +isPartOf()
    Organization1 : +hasPart()
    Organization1 : +hasMember()
    Level1 : +integer levelNumber
    Building1 : +hasBuildingComponent()
    SubBuilding1 : +Object type
    Lease1 : +dateTime leaseStart
    Lease1 : +dateTime leaseEnd
    Lease1 : +regulatedBy()
    Lease1 : +leasor()
    Lease1 : +leasee()
    Lease1 : +leaseOf()
    ArchitecturalAssetCollection1 : +includes()
    FurnitureCollection1 : +includes()
    TenantUnit1 : +includes()
    Campus1 : +operatedBy()
    Campus1 : +includes()
    RealEstate1 : +string propertyRegisterDesignation
    RealEstate1 : +ownedBy()
    RealEstate1 : +includes()
    Apartment1 : +includes()
    BarrierAsset1 : +double width
    BarrierAsset1 : +Object type
    BarrierAsset1 : +double thickness
    BarrierAsset1 : +string material
    BarrierAsset1 : +double height
    BarrierAsset1 : +string frameMaterial
    BarrierAsset1 : +double fireRating
    BarrierAsset1 : +toSpace()
    BarrierAsset1 : +fromSpace()
    Pump1 : +Object type
    Pump1 : +string pumpingMedia
    Pump1 : +double pressureCapacity
    Pump1 : +integer headCapacity
    Pump1 : +double flowCapacity
    HVACMixingBox1 : +boolean economizer
    Fan1 : +double nominalAirflow
    Fan1 : +double motorPower
    Fan1 : +double minAirflowRating
    Fan1 : +double maxAirflowRating
    Fan1 : +Object driveType
    Tank1 : +double tankCapacity
    Tank1 : +double systemPressure
    HeatTracing1 : +Object type
    HeatTracing1 : +double powerDensity
    HVACHeatingMethod1 : +Object type
    HVACHeatingMethod1 : +double outsideDiameter
    Valve1 : +double pressureCapacity
    Valve1 : +double pipeDiameter
    Valve1 : +double flowCapacity
    DuctConnection1 : +double size
    DuctConnection1 : +Object shape
    DuctConnection1 : +Object configuration
    ElectricalBus1 : +Object material
    ElectricalBus1 : +double currentRating
    HVACCoolingMethod1 : +Object type
    HVACCoolingMethod1 : +string refrigerantType
    HVACCoolingMethod1 : +double outsideDiameter
    ConveyanceEquipment1 : +string type
    PowerSensor1 : +double hasValue
    HumiditySensor1 : +double hasValue
    StatusSensor1 : +boolean hasValue
    MassSensor1 : +double hasValue
    PressureSensor1 : +double hasValue
    OccupancySensor1 : +boolean hasValue
    IlluminanceSensor1 : +double hasValue
    MotionSensor1 : +boolean hasValue
    PeopleCountSensor1 : +double hasValue
    TemperatureSensor1 : +double hasValue
    TVOCSensor1 : +double hasValue
    VolumeSensor1 : +double hasValue
    CO2Sensor1 : +double hasValue
    System1 : +string comment
    System1 : +Object service
    System1 : +isPartOf()
    Luminaire1 : +Object type
    SensorEquipment1 : +double wifiSignalStrength
    SensorEquipment1 : +double batteryPercentage
    ITHardware1 : +mountedInRack()
    DataNetworkEquipment1 : +mountedInRack()
    ITRack1 : +Object type
    ITRack1 : +Object mounting
    ITRack1 : +integer heightRUs
    AirHandlingUnit1 : +Object ventilationConfiguration
    AirHandlingUnit1 : +string refrigerantType
    AirHandlingUnit1 : +double nominalCoolingCapacity
    AirHandlingUnit1 : +double netSensibleCoolingCapacity
    AirHandlingUnit1 : +Object humidificationMethod
    AirHandlingUnit1 : +string filterType
    AirHandlingUnit1 : +Object dischargeDuctworkConfiguration
    AirHandlingUnit1 : +Object dehumidificationMethod
    AirHandlingUnit1 : +Object airflowModulation
    AirHandlingUnit1 : +Object supplyFan
    AirHandlingUnit1 : +Object secondaryCoolingMethod
    AirHandlingUnit1 : +Object returnFan
    AirHandlingUnit1 : +Object reHeatingMethod
    AirHandlingUnit1 : +Object primaryCoolingMethod
    AirHandlingUnit1 : +Object preHeatingMethod
    AirHandlingUnit1 : +Object mixingBox
    AirHandlingUnit1 : +Object exhaustFan
    AirHandlingUnit1 : +Object ventilationStrategy
    AirHandlingUnit1 : +Object zoneDelivery
    TerminalUnit1 : +double minAirflowRating
    TerminalUnit1 : +double maxAirflowRating
    TerminalUnit1 : +Object ductInlet
    AirFilter1 : +Object fan
    Damper1 : +Object service
    Damper1 : +Object leakageClass
    Damper1 : +Object bladeType
    Damper1 : +Object ductInlet
    CondensingUnit1 : +Object type
    CondensingUnit1 : +string refrigerantType
    CondensingUnit1 : +double nominalHeatingCapacity
    CondensingUnit1 : +double nominalCoolingCapacity
    CondensingUnit1 : +double netSensibleHeatingCapacity
    CondensingUnit1 : +double netSensibleCoolingCapacity
    CondensingUnit1 : +double eer
    HVACFan1 : +string type
    HVACFan1 : +Object fan
    HVACFan1 : +Object ductInlet
    UnitHeater1 : +Object type
    UnitHeater1 : +double nominalHeatingCapacity
    UnitHeater1 : +Object heatingMethod
    UnitHeater1 : +Object fan
    CoolingTower1 : +double nominalCoolingCapacity
    CoolingTower1 : +double flowCapacity
    CoolingTower1 : +Object fan
    Chiller1 : +Object type
    Chiller1 : +string refrigerantType
    Chiller1 : +double nominalCoolingCapacity
    Chiller1 : +double netSensibleCoolingCapacity
    Chiller1 : +Object compressorType
    Elevator1 : +integer personCapacity
    Elevator1 : +double weightCapacity
    Elevator1 : +double maxTravelSpeed
    Elevator1 : +double maxTravelDistance
    Elevator1 : +integer maxLandings
    ElevatorMachine1 : +double weightCapacity
    ElevatorMachine1 : +double motorPower
    Escalator1 : +double stepWidth
    Escalator1 : +double maxVerticalRise
    Escalator1 : +double maxTravelSpeed
    Escalator1 : +double inclination
    MovingWalkway1 : +double stepWidth
    MovingWalkway1 : +double maxTravelSpeed
    MovingWalkway1 : +double maxLength
    MovingWalkway1 : +double inclination
    Boiler1 : +Object type
    Boiler1 : +double tankCapacity
    Boiler1 : +double powerOutput
    Boiler1 : +double powerInput
    Boiler1 : +Object medium
    Boiler1 : +integer recovery100FRise
    AirCompressor1 : +double workingPressure
    AirCompressor1 : +double motorPower
    AirCompressor1 : +double freeAirDelivery
    ThermalMeter1 : +double volumeTotal
    ThermalMeter1 : +double volumeFlow
    ThermalMeter1 : +string type
    ThermalMeter1 : +double supplyTemp
    ThermalMeter1 : +double returnTemp
    ThermalMeter1 : +double energyTotal
    ThermalMeter1 : +double energyRate
    ThermalMeter1 : +double deltaTemp
    ThermalMeter1 : +subMeterOf()
    ThermalMeter1 : +measures()
    GasMeter1 : +string type
    GasMeter1 : +double massFlow
    GasMeter1 : +double mass
    GasMeter1 : +subMeterOf()
    GasMeter1 : +measures()
    WaterMeter1 : +double volumeFlow
    WaterMeter1 : +double volume
    WaterMeter1 : +string type
    WaterMeter1 : +double supplyTemp
    WaterMeter1 : +subMeterOf()
    WaterMeter1 : +measures()
    ElectricityMeter1 : +Object type
    ElectricityMeter1 : +double netPower
    ElectricityMeter1 : +double netEnergy
    ElectricityMeter1 : +double importPower
    ElectricityMeter1 : +double importEnergy
    ElectricityMeter1 : +double exportPower
    ElectricityMeter1 : +double exportEnergy
    ElectricityMeter1 : +subMeterOf()
    ThermalEnergySensor1 : +double hasValue
    ElectricalEnergySensor1 : +double hasValue
    MassFlowSensor1 : +double hasValue
    AirFlowSensor1 : +double hasValue
    WaterFlowSensor1 : +double hasValue
    FlowSetpoint1 : +double hasValue
    CO2Setpoint1 : +double hasValue
    TemperatureSetpoint1 : +double hasValue
    HumiditySetpoint1 : +double hasValue
    MeterEquipmentGroup1 : +includes()
    ElectricalEquipmentGroup1 : +includes()
    LightingEquipmentGroup1 : +includes()
    ICTEquipmentGroup1 : +includes()
    HVACEquipmentGroup1 : +includes()
    PlumbingEquipmentGroup1 : +includes()
    SecurityEquipmentGroup1 : +includes()
    ConveyanceEquipmentGroup1 : +includes()
    FireProtectionEquipmentGroup1 : +includes()
    EthernetRouter1 : +integer numberOfPorts
    EthernetRouter1 : +integer heightRUs
    EthernetSwitchPort1 : +string portSpeed
    EthernetSwitchPort1 : +integer poeType
    NetworkSecurityEquipment1 : +integer numberOfPorts
    NetworkSecurityEquipment1 : +integer heightRUs
    WirelessAccessPoint1 : +Object type
    WirelessAccessPoint1 : +Object mounting
    EthernetSwitch1 : +integer numberOfPorts
    EthernetSwitch1 : +integer heightRUs
    Server1 : +integer numberOfPorts
    Server1 : +integer heightRUs
    FanCoilUnit1 : +Object type
    FanCoilUnit1 : +string refrigerantType
    FanCoilUnit1 : +double nominalCoolingCapacity
    FanCoilUnit1 : +double netSensibleCoolingCapacity
    FanCoilUnit1 : +string filterType
    FanCoilUnit1 : +Object secondaryCoolingMethod
    FanCoilUnit1 : +Object primaryCoolingMethod
    FanCoilUnit1 : +Object fan
    SteamUnitHeater1 : +integer condensate
    ElectricUnitHeater1 : +double powerInput
    HotWaterUnitHeater1 : +double flowCapacity
    HVACShutOffValve1 : +Object type
    WaterFilter1 : +double workingPressure
    WaterFilter1 : +string type
    WaterFilter1 : +double tankCapacity
    WaterFilter1 : +double flowCapacity
    WaterFilter1 : +integer filtrationRating
    CeilingFan1 : +double maxRotationSpeed
    CeilingFan1 : +double bladeDiameter
    FireDamper1 : +double fireRating
    Switchgear1 : +string shortCircuitRating
    Switchgear1 : +double inputVoltage
    Switchgear1 : +Object inputPhases
    Switchgear1 : +Object mainBus
    ElectricalPanelboard1 : +string shortCircuitRating
    ElectricalPanelboard1 : +Object outputPhases
    ElectricalPanelboard1 : +double inputVoltage
    ElectricalPanelboard1 : +integer maxNumberOfPoles
    ElectricalPanelboard1 : +Object mainBus
    TransferSwitch1 : +Object poles
    TransferSwitch1 : +double mainsRating
    Busway1 : +string shortCircuitRating
    Busway1 : +double inputVoltage
    Busway1 : +Object inputPhases
    Busway1 : +Object mainBus
    Switchboard1 : +string shortCircuitRating
    Switchboard1 : +double inputVoltage
    Switchboard1 : +Object inputPhases
    Switchboard1 : +Object mainBus
    Transformer1 : +double voltageSecondary
    Transformer1 : +double voltagePrimary
    Transformer1 : +string type
    Transformer1 : +integer sizeKVA
    Transformer1 : +Object phases
    VariableFrequencyDrive1 : +Object type
    Generator1 : +double outputVoltage
    Generator1 : +Object outputPhases
    Generator1 : +string modeOfOperation
    Generator1 : +string fuelType
    Generator1 : +integer frequency
    Generator1 : +double dayTankCapacity
    Generator1 : +double bulkStorageCapacity
    Generator1 : +integer standbyPowerKVA
    Generator1 : +double standbyPower
    Generator1 : +integer primePowerKVA
    Generator1 : +double primePower
    UPS1 : +double runtime
    UPS1 : +integer powerOutputKVA
    UPS1 : +double powerOutput
    UPS1 : +double outputVoltage
    UPS1 : +Object outputPhases
    UPS1 : +double inputVoltage
    UPS1 : +Object inputPhases
    FlushometerValve1 : +double waterPerFlush
    FlushometerValve1 : +Object type
    FlushometerValve1 : +Object technology
    FlushometerValve1 : +mountedOn()
    Toilet1 : +double waterPerFlush
    Toilet1 : +Object installationType
    Faucet1 : +Object type
    Faucet1 : +double maxFlowRate
    Faucet1 : +integer numberOfHandles
    Faucet1 : +mountedOn()
    PlumbingShutOffValve1 : +Object type
    TankWaterHeater1 : +double tankCapacity
    PlumbingStorageTank1 : +Object type
    PlumbingStorageTank1 : +Object arrangement
    PlumbingExpansionTank1 : +Object type
    FanPoweredBox1 : +Object configuration
    FanPoweredBox1 : +Object fan
    VAVBoxReheat1 : +Object reHeatingMethod
    FanCoilUnitReheat1 : +Object reHeatingMethod
    AutomaticTransferSwitch1 : +Object transitionType
    AutomaticTransferSwitch1 : +Object switchingMechanism
    ElectricalPanelboardMCB1 : +double MCBRating
    UrinalFlushometer1 : +double waterPerFlush
    ToiletTank1 : +Object flushingType
    GasTanklessWaterHeater1 : +double powerInput
    ElectricTanklessWaterHeater1 : +double powerInput
    ElectricTankWaterHeater1 : +double powerInput
    GasTankWaterHeater1 : +double powerInput
    FireSprinklerHead1 : +Object type
    FireSprinklerHead1 : +integer kFactorMetric
    FireSprinklerHead1 : +integer kFactorImperial
    FanPoweredBoxReheat1 : +Object reHeatingMethod
    SprinklerShutOffValve1 : +Object type
