classDiagram
    AirHandlingUnit1 <|-- HVACEquipment1
    HVACWaterTreatment1 <|-- HVACEquipment1
    HVACTank1 <|-- Tank1
    HVACTank1 <|-- HVACEquipment1
    TerminalUnit1 <|-- HVACEquipment1
    HVACPump1 <|-- Pump1
    HVACPump1 <|-- HVACEquipment1
    HeatExchanger1 <|-- HVACEquipment1
    AirFilter1 <|-- HVACEquipment1
    Damper1 <|-- HVACEquipment1
    CondensingUnit1 <|-- HVACEquipment1
    HVACValve1 <|-- Valve1
    HVACValve1 <|-- HVACEquipment1
    HVACFan1 <|-- HVACEquipment1
    UnitHeater1 <|-- HVACEquipment1
    HVACHeatTracing1 <|-- HeatTracing1
    HVACHeatTracing1 <|-- HVACEquipment1
    CoolingTower1 <|-- HVACEquipment1
    Chiller1 <|-- HVACEquipment1
    CAVBox1 <|-- TerminalUnit1
    FanCoilUnit1 <|-- TerminalUnit1
    VAVBox1 <|-- TerminalUnit1
    SteamUnitHeater1 <|-- UnitHeater1
    ElectricUnitHeater1 <|-- UnitHeater1
    HotWaterUnitHeater1 <|-- UnitHeater1
    HVACBackflowPreventer1 <|-- HVACValve1
    HVACSolenoidValve1 <|-- HVACValve1
    HVACShutOffValve1 <|-- HVACValve1
    HVACPressureReducingStation1 <|-- HVACValve1
    HVACGlobeValve1 <|-- HVACValve1
    HVACPressureReducingValve1 <|-- HVACValve1
    HVACCheckValve1 <|-- HVACValve1
    HVACBalancingValve1 <|-- HVACValve1
    MakeupAirUnit1 <|-- AirHandlingUnit1
    RooftopUnit1 <|-- AirHandlingUnit1
    DedicatedOutdoorAirSystem1 <|-- AirHandlingUnit1
    WaterFilter1 <|-- HVACWaterTreatment1
    CeilingFan1 <|-- HVACFan1
    ExhaustFan1 <|-- HVACFan1
    StairPressurizationFan1 <|-- HVACFan1
    TransferFan1 <|-- HVACFan1
    SupplyFan1 <|-- HVACFan1
    BackdraftDamper1 <|-- Damper1
    SmokeDamper1 <|-- Damper1
    FireDamper1 <|-- Damper1
    FanPoweredBox1 <|-- VAVBox1
    VAVBoxReheat1 <|-- VAVBox1
    FanCoilUnitReheat1 <|-- FanCoilUnit1
    FireSmokeDamper1 <|-- FireDamper1
    FanPoweredBoxReheat1 <|-- FanPoweredBox1
    AirHandlingUnit1 : +Object ventilationConfiguration
    AirHandlingUnit1 : +string refrigerantType
    AirHandlingUnit1 : +double nominalCoolingCapacity
    AirHandlingUnit1 : +double netSensibleCoolingCapacity
    AirHandlingUnit1 : +Object humidificationMethod
    AirHandlingUnit1 : +string filterType
    AirHandlingUnit1 : +Object dischargeDuctworkConfiguration
    AirHandlingUnit1 : +Object dehumidificationMethod
    AirHandlingUnit1 : +Object airflowModulation
    AirHandlingUnit1 : +Object supplyFan
    AirHandlingUnit1 : +Object secondaryCoolingMethod
    AirHandlingUnit1 : +Object returnFan
    AirHandlingUnit1 : +Object reHeatingMethod
    AirHandlingUnit1 : +Object primaryCoolingMethod
    AirHandlingUnit1 : +Object preHeatingMethod
    AirHandlingUnit1 : +Object mixingBox
    AirHandlingUnit1 : +Object exhaustFan
    AirHandlingUnit1 : +Object ventilationStrategy
    AirHandlingUnit1 : +Object zoneDelivery
    TerminalUnit1 : +double minAirflowRating
    TerminalUnit1 : +double maxAirflowRating
    TerminalUnit1 : +Object ductInlet
    AirFilter1 : +Object fan
    Damper1 : +Object service
    Damper1 : +Object leakageClass
    Damper1 : +Object bladeType
    Damper1 : +Object ductInlet
    CondensingUnit1 : +Object type
    CondensingUnit1 : +string refrigerantType
    CondensingUnit1 : +double nominalHeatingCapacity
    CondensingUnit1 : +double nominalCoolingCapacity
    CondensingUnit1 : +double netSensibleHeatingCapacity
    CondensingUnit1 : +double netSensibleCoolingCapacity
    CondensingUnit1 : +double eer
    HVACFan1 : +string type
    HVACFan1 : +Object fan
    HVACFan1 : +Object ductInlet
    UnitHeater1 : +Object type
    UnitHeater1 : +double nominalHeatingCapacity
    UnitHeater1 : +Object heatingMethod
    UnitHeater1 : +Object fan
    CoolingTower1 : +double nominalCoolingCapacity
    CoolingTower1 : +double flowCapacity
    CoolingTower1 : +Object fan
    Chiller1 : +Object type
    Chiller1 : +string refrigerantType
    Chiller1 : +double nominalCoolingCapacity
    Chiller1 : +double netSensibleCoolingCapacity
    Chiller1 : +Object compressorType
    FanCoilUnit1 : +Object type
    FanCoilUnit1 : +string refrigerantType
    FanCoilUnit1 : +double nominalCoolingCapacity
    FanCoilUnit1 : +double netSensibleCoolingCapacity
    FanCoilUnit1 : +string filterType
    FanCoilUnit1 : +Object secondaryCoolingMethod
    FanCoilUnit1 : +Object primaryCoolingMethod
    FanCoilUnit1 : +Object fan
    SteamUnitHeater1 : +integer condensate
    ElectricUnitHeater1 : +double powerInput
    HotWaterUnitHeater1 : +double flowCapacity
    HVACShutOffValve1 : +Object type
    WaterFilter1 : +double workingPressure
    WaterFilter1 : +string type
    WaterFilter1 : +double tankCapacity
    WaterFilter1 : +double flowCapacity
    WaterFilter1 : +integer filtrationRating
    CeilingFan1 : +double maxRotationSpeed
    CeilingFan1 : +double bladeDiameter
    FireDamper1 : +double fireRating
    FanPoweredBox1 : +Object configuration
    FanPoweredBox1 : +Object fan
    VAVBoxReheat1 : +Object reHeatingMethod
    FanCoilUnitReheat1 : +Object reHeatingMethod
    FanPoweredBoxReheat1 : +Object reHeatingMethod
